### PR TITLE
Fix issue with threading

### PR DESCRIPTION
**Pull request by 113408**

### CODE REVIEW

**Comment by theblitz** [comment]
@113408 
Hey.
Can you please the problem you found and the fix before I do the pull.

Just want to be sure we are on the same page.

**Comment by 113408** [comment]
Hey @theblitz ,
First of all, I would like to thank you for the great job you did on this library. Very useful !
The change is to be able to use the Observable from different threads. without the postValue, the devs would have to change every time the context to the main one before pushing items to the Collections/Maps

Based on the documentation:

setValue():

>  Sets the value. If there are active observers, the value will be dispatched to them. This method must be called from the main thread.

postValue():

> Posts a task to a main thread to set the given value. If you called this method multiple times before a main thread executed a posted task, only the last value would be dispatched.

**Comment by theblitz** [comment]
@113408 
Many thanks.
Merged it in.

**Comment by 113408** [comment]
do you think you can release a new version ?
If not, would you accept a PR to move the project to jitpack.io ?

**Comment by theblitz** [comment]
Sorry.
I completely forgot.
Will do so in the next few days.

**Pull request merged**
