### PR TITLE
Fix #1 and #2

### LINKED ISSUE #1: Map `put` sends a `Clear` action instead of a `Put` action.
Map `put` sends a `Clear` action instead of a `Put` action.

```
    fun put(key: X, value: Y): Y? {
        val resultValue = map!!.put(key, value)
        signalChanged(action = ObservableCollectionsAction.Clear, actionKey = key, actionValue = value, resultValue = resultValue)
        return resultValue
    }

    fun putAll(from: Map<out X, Y>) {
        map!!.putAll(from)
        signalChanged(action = ObservableCollectionsAction.Clear, actionMap = from)
        
    }
```

### PR DESCRIPTION
**Pull request by jcogilvie**

### CODE REVIEW

**Review by theblitz — CHANGES_REQUESTED** [review]
You need a small change to the fix:

Line 117 should send PutAll instead of Put

**Comment by jcogilvie** [comment]
I didn't send `PutAll` because it didn't exist in the enum.  I'll add it.

**Comment by jcogilvie** [comment]
ack, habitually committed with `am`.  backing some of that out...

**Comment by jcogilvie** [comment]
All set now.

**Pull request merged**
